# theme.toml template for a Hugo theme
# See https://github.com/guangzhengli/hugo-theme-ladder/blob/master/theme.toml for an example

name = "Hugo Ladder"
license = "MIT"
licenselink = "https://github.com/guangzhengli/hugo-theme-ladder/blob/master/LICENSE"
description = ""
homepage = "http://guangzhengli.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "guangzhengli"
  homepage = "http://guangzhengli.com/"
